version: "3.3"
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432