version: "3.3"
services:

  api:
    build:
      context: ./docker/api
    volumes:
      # .gitを含めるためにルートごとマウントする
      - ./:/workspace:cached
      - ./docker/api/init.sh:/init.sh
    working_dir: "/workspace/api"
    command: "sh /init.sh"
    env_file:
      - .env
    depends_on:
      - db

  front:
    image: node:16
    command: sh -c "npm install && npm run dev"
    working_dir: "/workspace/front"
    volumes:
      # .gitを含めるためにルートごとマウントする
      - ./:/workspace:cached
      - front_node_modules:/workspace/front/node_modules
    depends_on:
      - api

  db:
    image: postgres:14
    env_file:
      - .env

  search-engine:
    build:
      context: ./docker/search
    env_file:
      - .env
    environment:
      - TZ=${OS_TIMEZONE}
      - discovery.type=single-node

volumes:
  front_node_modules:
