version: "3.3"
services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  front:
    image: node:16
    command:  sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./front:/app:chached
      - front_node_modules:/app/node_modules
    ports:
      - 3000:3000

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  front_node_modules:
