version: "3.3"
services:

  api:
    ports:
      - 8000:8000

  front:
    ports:
      - 3000:3000

  search-dashboard:
    image: opensearchproject/opensearch-dashboards:1.3.2
    environment:
      OPENSEARCH_HOSTS: "https://search-engine:9200"
    ports:
      - 5601:5601
    depends_on:
      - search-engine
