version: "3.3"
services:

  api:
    build:
      context: ./docker/api
    volumes:
      - ./api:/api
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "poetry install && poetry run uvicorn app.main:app --host 0.0.0.0 --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  front:
    image: node:16
    command:  sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./front:/app:chached
      - front_node_modules:/app/node_modules
    ports:
      - 3000:3000

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432

  search-engine:
    image: opensearchproject/opensearch:1.3.2
    environment:
      - TZ=${OS_TIMEZONE}
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true

volumes:
  front_node_modules:
