version: "3.3"
services:

  api:
    build:
      context: ./docker/api
    volumes:
      - ./api:/api
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "poetry install && poetry run uvicorn app.main:app --host 0.0.0.0 --reload"
    env_file:
      - .env
    depends_on:
      - db

  front:
    image: node:16
    command:  sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./front:/app:chached
      - front_node_modules:/app/node_modules
    depends_on:
      - api

  db:
    image: postgres:14
    env_file:
      - .env

  search-engine:
    build:
      context: ./docker/search
    env_file:
      - .env
    environment:
      - TZ=${OS_TIMEZONE}
      - discovery.type=single-node

volumes:
  front_node_modules:
